### ISSUE TITLE
Why wobble rings with a two-part middle ring?

### ISSUE THREAD

**Issue by keenle** [FlorentBroise/BRS-Printers-Mod#2]
Hi there! 

Looking at your wobble rings remix https://store.brs-engineering.com/fr-us/products/decoupleur-oldham and not sure how to explain some of remix design decisions.... Could you tell:

1. Why middle ring from two pieces?
2. Why fixing bolt in the bottom ring?

Attaching this image with in-place questions:
<img width="1142" alt="Screen Shot 2022-08-12 at 12 59 24 PM" src="https://user-images.githubusercontent.com/5788919/184410807-638e3c99-33d8-438f-9973-794bfbb0a61c.png">

Thank you!

**Comment by FlorentBroise** [comment]
Hello Keenle


The m6 headless screw / or grease tip, is here to opturate the grease port of the nut, you see a small recess for the ease of adaptation

The 2 middle parts where basically made to structurally enhence the stiffness of the ring, as the pressure can be tremendous. For 300-400-500 version it can be of if using 6mm bed, and a robist 100% infill mùaterial and hase been design to last (no bending over time)

I made recently a 1 part middle ring a bit different which can sustain loads, it will be out soon


As you may know, this design in other community (Hevort) suffer a makor issue which is bending over time, loosing the spec, usage, reliability, repetability. I wanted a stiff-proof design to accomodate longevity to be use from 6mm to 12mm Alu cast bed, OR like a company ask, a 20mm granit bed (it exists yes^^).


Splitting the central ring in 2 and adding 4x 45° screws attachment has been proven to enhance the longevity under loads way over the maximum needed.


That is why


that said a mono central ring can do the Job with the proper material and the proper context.


As i manufacture it, I want to stick to only 1 design for ease of managment, so this design choice was made considering all of this!


Have a nice day


[https://drive.google.com/uc?id=1ppS0cTVcHU27ylrWxZPxJkv_RZeHxkHQ]

[facebook]<https://www.facebook.com/FlorentBroiseEngineering>
        [linkedin] <https://www.linkedin.com/in/florent-broise-2a1896101/>




Florent Broise

3D-Printing engineer

 BRS Engineering




[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
        0645326660<tel:0645326660>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
        ***@***.******@***.***>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
        www.brs-engineering.com/<https://www.brs-engineering.com/>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
        45 Ter rue de la résistance, 38950, St Martin Le Vinoux






________________________________
De : keenle ***@***.***>
Envoyé : vendredi 12 août 2022 19:20:43
À : FlorentBroise/BRS-Printers-Mod
Cc : Subscribed
Objet : [FlorentBroise/BRS-Printers-Mod] Why wobble rings with a two-part middle ring? (Issue #2)


Hi there!

Looking at your wobble rings remix https://store.brs-engineering.com/fr-us/products/decoupleur-oldham and not sure how to explain some of remix design decisions.... Could you tell:

  1.  Why middle ring from two pieces?
  2.  Why fixing bolt in the bottom ring?

Attaching this image with in-place questions:
[Screen Shot 2022-08-12 at 12 59 24 PM]<https://user-images.githubusercontent.com/5788919/184410807-638e3c99-33d8-438f-9973-794bfbb0a61c.png>

Thank you!

**Comment by FlorentBroise** [comment]
Hi there! I've uploaded a central ring update in 1 part to match ease of manufactuing, Can be use with 6mm bed without issues so far after few fatigue tests since this summer/ https://raw.githubusercontent.com/FlorentBroise/BRS-Printers-Mod/main/cad/RingUnifiedv2.step
